[[build.env]]
name='BP_PHP_SERVER'
value='nginx'

[[build.env]]
name='BP_COMPOSER_INSTALL_OPTIONS'
value = [
  'cp .env.example .env',
  '--prefer-dist --ignore-platform-reqs',
  'php artisan cache:clear'
]

[[build.env]]
name='BP_PHP_WEB_DIR'
value='public'